// C4D-DialogResource
DIALOG %!PluginNameAsIdentifier!%
{
  NAME IDS_DIALOG_TITLE; CENTER_V; ALIGN_LEFT; 
  
  GROUP IDC_GROUP_WRAPPER
  {
    NAME IDS_GROUP_WRAPPER; ALIGN_TOP; SCALE_H; 
    BORDERSIZE 4, 4, 4, 4; 
    COLUMNS 1;
    SPACE 4, 4;
    
    GROUP IDC_GROUP_SETTINGS
    {
      NAME IDS_GROUP_SETTINGS; ALIGN_TOP; ALIGN_LEFT; 
      BORDERSTYLE BORDER_NONE; BORDERSIZE 0, 0, 0, 0; 
      COLUMNS 1;
      
      
    }
    SEPARATOR { SCALE_H; }
    GROUP IDC_GROUP_BUTTONS
    {
      NAME IDS_GROUP_BUTTONS; ALIGN_TOP; CENTER_H; 
      BORDERSIZE 0, 0, 0, 0; 
      COLUMNS 2;
      SPACE 4, 4;
      
      BUTTON IDC_BUTTON_CANCEL { NAME IDS_BUTTON_CANCEL; ALIGN_TOP; CENTER_H; }
      BUTTON IDC_BUTTON_DOIT { NAME IDS_BUTTON_DOIT; ALIGN_TOP; CENTER_H; }
    }
    GROUP IDC_DUMMY
    {
      NAME IDS_DUMMY; ALIGN_TOP; SCALE_H; 
      BORDERSIZE 0, 0, 0, 0; 
      COLUMNS 1;
      SPACE 4, 4;
      
      
    }
  }
}